### ISSUE TITLE
StrEnum require Python3.11 instead of 3.10

### ISSUE THREAD

**Issue by AvengerMoJo** [dcermak/scm-staging#2]
scm_staging/person.py:10:class PersonRole(enum.StrEnum):
scm_staging/request.py:16:class RequestStatus(enum.StrEnum):
scm_staging/request.py:36:class RequestActionType(enum.StrEnum):
scm_staging/request.py:74:class SourceUpdate(enum.StrEnum):

should I patch and replace them with Enum?

**Comment by dcermak** [comment]
Hm, that would require adding additional code so that `__str__()` is implemented correctly. I would be much more tempted to just bump the python requirement to `^3.11` to be honest :sweat_smile:. Or would that be an issue for you?

**Comment by AvengerMoJo** [comment]
na, I can update the requirement to 3.11 instead then that's why I didn't PR this :)

**Comment by dcermak** [comment]
That would be lovely!
